apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: demo-virtualservice
spec:
  hosts:
  - "kubedemo.kkzonie.com"
  gateways:
  - istio-system/argocd-gateway
  http:
  - match:
    - uri:
        prefix: /demo
    route:
    - destination:
        host: demo
        port:
          number: 8080